### ISSUE TITLE
SyntaxError: Unexpected token '||='

### ISSUE THREAD

**Issue by v1ack** [cibernox/precompile-intl-runtime#21]
Hello
Looks like there is an error in commit 76330a3fee38ff02b70e824c3977118435e7a7fd

precompile-intl-runtime/dist/modules/stores/formatters.js
SyntaxError: Unexpected token '||='

**Comment by cibernox** [comment]
Yeah, technically that's valid javascript but only in node 16 and above. I refactored so it can work in not-so-state-of-the-art node versions.

**Comment by cibernox** [comment]
Thanks for reporting, since I use node 16 I didn't notice that one 🙇
