### ISSUE TITLE
Prioritize first language in header (`getLocaleFromAcceptLanguageHeader`)

### ISSUE THREAD

**Issue by venashial** [cibernox/precompile-intl-runtime#31]
Currently, the `getLocaleFromAcceptLanguageHeader()` function can return `undefined` when the available languages all have region codes for a certain language, but the header does not. For example:

```js
getLocaleFromAcceptLanguageHeader('fr', ['fr-BE', 'fr-CA', 'fr-FR']) // returns `undefined`
```

### My current solution
```diff
export const getLocaleFromAcceptLanguageHeader = (
	header: string | null,
	availableLocales?: string[]
): string | undefined => {
	...

	// If availableLocales is not defined return the first language from header
	if (!availableLocales || availableLocales.length === 0) return locales[0].locale

+++	if (availableLocales.includes(locales[0].locale)) {
+++		return locales[0].locale
+++	}
+++
+++	for (const available of availableLocales) {
+++		if (available.split('-')[0] === locales[0].locale) {
+++			return available
+++		}
+++	}

	availableLocales = availableLocales.map((l) => l.toLowerCase())

	// Check full match
	for (const locale of locales) {
		if (availableLocales.includes(locale.locale.toLowerCase())) return locale.locale
	}
	...
```

**Comment by vekunz** [comment]
I think this is a great addition to this function. But I would move the for loop after the `Check base language match` loop, because of specificity. And then the additional `if` should no longer be necessary.

**Comment by venashial** [comment]
The issue with doing it that way, I encountered, was that the function would pick a much lower prioritized language over a higher one that had a base language match. In this example, `fr-FR` would probably be the better choice:
```js
getLocaleFromAcceptLanguageHeader('fr, fr-CA;q=0.9, en;q=0.8', ['fr-FR', 'en']) // returns `en`
```

**Comment by vekunz** [comment]
This seems right. I think that the language matching needs to be rewritten, to cover all cases. I try to solve this.

**Comment by vekunz** [comment]
I created a pull request to solve this issue. Can you look into the changes? https://github.com/cibernox/precompile-intl-runtime/pull/32

**Comment by cibernox** [comment]
I didn't forget about this but I've been to busy this week. Tomorrow I shall check the PR

**Comment by cibernox** [comment]
I believe this can be closed now. Thanks!

**Comment by venashial** [comment]
Thanks, #32 covers a lot more cases.

I'm still having a few minor issues with matching bases between regional variants, take this case:
```js
console.log(getLocaleFromAcceptLanguageHeader('es-AR', ['es-ES'])) // returns `undefined`
```

**Comment by vekunz** [comment]
> ```js
> console.log(getLocaleFromAcceptLanguageHeader('es-AR', ['es-ES'])) // returns `undefined`
> ```
This seems to be right, because between "es-AR" and "es-ES" is no actual match. But I think that this is not a a big problem, because most browsers add the base language by default. So a browser would normally not send "es-AR" but "es-AR,es"
