### ISSUE TITLE
locale store initialization sets value of`<html lang="xx">` attribute to empty string

### ISSUE THREAD

**Issue by dominikg** [cibernox/precompile-intl-runtime#36]
https://github.com/cibernox/precompile-intl-runtime/blob/8198e7ba7b2783df4c447f20400fb727c48d7742/src/stores/locale.ts#L7

+

https://github.com/cibernox/precompile-intl-runtime/blob/8198e7ba7b2783df4c447f20400fb727c48d7742/src/stores/locale.ts#L13

= `<html lang="">`

This causes a problem when you want to detect the user language in SSR and load the result of that detection in the client side initialization. Even though the server sends `<html lang="en">`, the client code can't read it after importing the store.

See https://github.com/dominikg/kit-with-svelte-intl-precompile  for an example with sveltekit

This can be worked around by reading the value beforehand or putting it in a separate property like in head`<meta http-equiv="content-language" content="%lang%" />` but thats not ideal.

Proposed solution:
Ignore the initial value of '', or initialize it with the current value of document.documentElement.lang

**Comment by cibernox** [comment]
Naively I'd think that not setting the value unless it's different from an empty string is better. At least we make sure we don't display a wrong value. The value of  document.documentElement.lang might not be a locale that the app actually supports, resulting in an invalid locale.

**Comment by cibernox** [comment]
I published 0.8.1 with a fix.
